### ISSUE TITLE
Questions about the dataset.

### ISSUE THREAD

**Issue by AlanMorningLight** [nirmalsenthilnathan/Open-set-domain-adaptatin-HSI-classification-using-GAN#1]
Thank you very much for uploading this code which is of great help to me. because of lacking the dataset,.the code can't be run. If you upload your datasets such as  PaviaU_5.csv and PaviaU.csv, it would be great nice. Thank you very much.

**Comment by nirmalsenthilnathan** [comment]
Hi Alan,

Thanks for your comment. we have made number of dataset for testing purpose by making modifications to existing PaviaU, SalinasA and Salinas. I have uploaded SalinasA.csv (Source) and Salinas.csv(Target) in the repository. kindly use this for running the code after making necessary changes such as number of classes, arguments and few other minor things. In case you need all the dataset with description, please drop a mail at nirmalsenthilnathan@gmail.com.
